### ISSUE TITLE
Endpoint service name must be valid string for user agent

### ISSUE THREAD

**Issue by sixinli** [palantir/dialogue#1143]
## What happened?

service name seems to be any string from the api but it actually needs to be valid for user agent, which is `[a-zA-Z][a-zA-Z0-9\\-]*`

## What did you want to happen?

either skip putting service name to user agent when it doesnt match the format, or give an earlier error

**Comment by carterkozak** [comment]
Ouch, good catch. Can you show me where/how this happened?
