### ISSUE TITLE
StickyClientFactory creates a new dialogue client for each request to getCurrentBest for a client interface

### ISSUE THREAD

**Issue by saurabhshukla92** [palantir/dialogue#1308]
Creating a new dialogue client involves a lot of potentially expensive allocations, like creating metric registries etc. We can avoid creating clients for the same client interface passed to the sticky client factory by simply caching the client we return.

Relevant code is here: https://github.com/palantir/dialogue/blob/develop/dialogue-clients/src/main/java/com/palantir/dialogue/clients/ReloadingClientFactory.java#L238

**Comment by jkozlowski** [comment]
It doesn't create a client (those are still created correctly), but the initialization of metrics etc. happens on each of these calls. I'll see if there's anything we can do, we'd need basically reverse the flow of operations here a little bit.

**Comment by carterkozak** [comment]
I'd expect this to help: #1399
