### ISSUE TITLE
Channel should be closeable

### ISSUE THREAD

**Issue by carterkozak** [palantir/dialogue#339]
## What happened?

Currently we don't have a mechanism to release http client resources when a channel closes. Unlike other clients OkHttp doesn't need to be closed, however without a proper close mechanism we may leave QueuedChannel queued futures waiting indefinitely, and box ourselves out of properly using other clients.

## What did you want to happen?

Channels should be able to clean up resources.

**Comment by carterkozak** [comment]
Instead of Channel being closeable I think we want the concept of a client (ChannelFactory) that is closeable.
Combined with a mechanism to signal to waiting channels (esp LimitedChannel) that requests may be submitted, queued/retrying requests will attempt to flow through the closed client and quickly be rejected.

Related: #340

**Comment by iamdanfox** [comment]
Ooh I think we can close this out, because WC now cleans up the apache [CloseableClient](https://github.com/palantir/dialogue/blob/93c0807ce916e99b54ef9b72ded4088b71c95366/dialogue-apache-hc4-client/src/main/java/com/palantir/dialogue/hc4/ApacheHttpClientChannels.java#L148)

**Comment by iamdanfox** [comment]
Actually nvm this issue is specific to cleaning up queued stuff, not apache stuff.

**Comment by ferozco** [comment]
I don't this applies any longer since we are no longer using a queue

**Comment by carterkozak** [comment]
Agreed
