### ISSUE TITLE
Provide a channel factory API to transparently test different client implementations

### ISSUE THREAD

**Issue by carterkozak** [palantir/dialogue#340]
## What happened?

Our different client implementations require different pieces of data to be used.

## What did you want to happen?

We should provide a channel factory (Client?) API to create channels from a ClientConfiguration + metric registry so we can transparently drop in alternative implementations.

**Comment by carterkozak** [comment]
Channel factory could be named `DialogueClient`.

**Comment by ferozco** [comment]
Closed by #492
