### ISSUE TITLE
Http 308 (QosException.RetryOther)

### ISSUE THREAD

**Issue by iamdanfox** [palantir/dialogue#456]
## What happened?

In theory servers can throw a QosException.RetryOther with a specific url, which gets mapped to a HTTP 308 and Location header. In practise, I searched Aries and can't find any request logs with this status code.

## What did you want to happen?

I certainly makes life simpler if we just don't implement this (as we don't have to keep track of uris), but if we're going to pick this stance I think we need to document it a bit better.

**Comment by carterkozak** [comment]
This would be a good time to spec out a similar exception type for client failures that don’t make it to a server (no status code). Feign uses FeignException, I recall that being handled specifically in some code, do we want a similar type for conjure clients?

**Comment by jkozlowski** [comment]
AtlasDB timelock-server returns specific URLs to indicate the leader to talk to. It is part of the leader discovery logic for clients.

**Comment by iamdanfox** [comment]
Naive implementation landed here https://github.com/palantir/dialogue/pull/648
