### ISSUE TITLE
Dialogue clients for void endpoints never throw

### ISSUE THREAD

**Issue by gatesn** [palantir/dialogue#586]
## What happened?

Dialogue clients for void endpoints never throw.

## What did you want to happen?
My server was returning 400s, 405s, etc. I'd expect the client to throw a RemoteException or UnknownRemoteException.

Looks like the `EmptyBodyDeserializer` just shrugs and closes the response body.

**Comment by carterkozak** [comment]
I believe this is resolved in the latest release

**Comment by gatesn** [comment]
Will upgrade and try it out, thanks

**Comment by carterkozak** [comment]
See #575

**Comment by gatesn** [comment]
Yup looks good
