### ISSUE TITLE
No good option for black holed server nodes

### ISSUE THREAD

**Issue by bwaldrep** [palantir/dialogue#615]
## What happened?

We've seen a few incidents where a client was talking to a 3-node server using a round-robin strategy to spread load evenly. For various reasons (typically a host-level issue) one server node will become unresponsive and black hole all incoming requests until they hit their client timeout. After a minute or two of continued round-robin nearly all client's worker threads are blocked waiting on requests to the bad node to time out, causing an outage.

## What did you want to happen?

None of the current node selection strategies handle this case well, as seen in the `black_hole*` simulation results. Ideally we could be robust to one of multiple server nodes entering this state and still make some progress using the remaining healthy nodes.

@iamdanfox had a promising prototype here: #373

**Comment by iamdanfox** [comment]
So https://github.com/palantir/dialogue/pull/373 has now merged, and people anyone who has set `NodeSelectionStrategy.ROUND_ROBIN` will get it from dialogue 1.28.0 onwards. In the `black_hole` simulation where pin_until_error delivers 56% client-perceived success, the new 'Balanced' implementation delivers 91.3% client-perceived success :D

See the [simulation graphs](https://github.com/palantir/dialogue/blob/9061e48ae0c0b710fb829c75bd93c36d7445e3be/simulation/src/test/resources/report.md#black_holeconcurrency_limiter_round_robin)
