### ISSUE TITLE
Following 308 redirects go through the exponential backoff

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/dialogue#728]
## What happened?

Dialogue 1.38.0

As the title suggests. I have a test on AtlasDB that verifies that a server that gives you looping 308s for ten seconds and then starts returning 200s has us recover quickly.

```java
    @Test
    public void recoversQuicklyOnceServerCeasesToSpam308s() {
        server.stubFor(TIMESTAMP_MAPPING.willReturn(aResponse()
                .withStatus(308)
                .withHeader("Location", getUriForPort(serverPort))));

        Instant start = Instant.now();
        ExecutorService ex = PTExecutors.newSingleThreadExecutor(true);
        ex.submit(this::scheduleServerRecoveryAfterTenSeconds);

        makeTimestampsRequest();
        assertThat(Instant.now())
                .as("should recover in a second after things are good again")
                .isBefore(start.plus(Duration.ofSeconds(11)));
        ex.shutdown();
    }

    private ConjureGetFreshTimestampsResponse makeTimestampsRequest() {
        return conjureTimelockService.getFreshTimestamps(
                AuthHeader.valueOf("Bearer unused"), CLIENT, ConjureGetFreshTimestampsRequest.of(10));
    }
```

This succeeds with a conjureTimelockService provided via CJR but fails with one from Dialogue (in particular, the assertion fails, though no exception is thrown).

Poking around in the debugger it looks like 308s go through the same code path as 429s and 503s, including the exponential backoff.

## What did you want to happen?

I'd have liked the 308s to be followed immediately - these aren't indicative of QoS problems that 429s or 503s would seem to be, so unclear if waiting is generally helpful here.

**Comment by carterkozak** [comment]
That's fair, I don't think there's any reason to back off in this case.
